runtime: php55
api_version: 1
threadsafe: true

handlers:

- url: /css
  static_dir: css


- url: /.*
  script: index.php
  
- url: /img
  static_dir: .*
  
- url: /config
  static_dir: config
  
# Serve static files as static resources.
# - url: /(.+\.(gif|png|jpg|svg|webp|jpeg|js))$
  # static_files: \1
  # upload: .+\.(gif|png|jpg|svg|webp|jpeg|js)$
  
- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$